### PR TITLE
goToDate wrong day bug fixed

### PR DESCRIPTION
**Pull request by KimPark89**
Fixes goToDate bug that causes that the calendar sometimes goes to 1
day before the chosen date

### CODE REVIEW

**Comment by alamkanak** [comment]
So it was a time zone issue then!
@caske33 Did you happen to test this out?

**Comment by caske33** [comment]
I've tested my version 94230c5 which does the division before the subtraction because I think there was a bug there too. (I'm not sure in which branch I commited that, but it's there in my fork).

I'm not sure if it solves a bug (I don't know how to recreate the bug). but it at least doesn't create one. And I can scroll one day at a time for over 3 months without a problem...

**Comment by alamkanak** [comment]
@KimPark89 Can you provide a way to reproduce the bug in the current version of the lib? Need to test it before I merge.

**Comment by KimPark89** [comment]
@alamkanak Very easy. Actually we are in "daylight saving time" so you just need to go to a date in the past in "standard time" to reproduce the bug. For example go to 20 March 2015. The destination will be 21 March 2015.

**Pull request merged**
