### PR TITLE
Changing typeface of all text

### PR DESCRIPTION
**Pull request by chrissd23**
Hi, 
this PR should fix this issues #219 @caske33

### CODE REVIEW

**Comment by chrissd23** [comment]
Yes, you are right, that's a mistake :grin:

I'll change it.

**Comment by chrissd23** [comment]
@caske33  I fix it.

**Comment by caske33** [comment]
Can you squash the commits?

**Comment by chrissd23** [comment]
Sorry it doesn't work :(

**Comment by chrissd23** [comment]
I create new clean pull request

**Pull request closed without merging**
