### PR TITLE
fix rotation changes

### PR DESCRIPTION
**Pull request by mannungo**
Hi! I have a problem with manage rotation in a code like this one:

```javascript
public void onConfigurationChanged(Configuration newConfig) {
	super.onConfigurationChanged(newConfig);
	weekview.setNumberOfVisibleDays(getResources().getConfiguration().orientation == configuration.ORIENTATION_LANDSCAPE ? 7 : 1 )
}
```

this fix resolving that.

### CODE REVIEW

**Comment by caske33** [comment]
The 2nd commit should definitly not be in this PR.

And can you make the super call the first in the method?

**Comment by m4droid** [comment]
Second commit removed and the method call is on top now.

**Comment by caske33** [comment]
Can you squash this into one commit?

**Comment by m4droid** [comment]
Done

**Pull request merged**
