### PR TITLE
improve scroll/fling performance

### LINKED ISSUE #139: Scroll is slow in new version 1.2.3
I have tried 1.2.0, 1.2.1 and 1.2.3. The scroll runs very smooth in 1.2.0 and 1.2.1, but it is very slow in 1.2.3.

### PR DESCRIPTION
**Pull request by marunjar**
first try to fix #139

i tried to change it to be more like the examples in android doc

1: https://developer.android.com/training/gestures/scale.html
2: https://developer.android.com/training/gestures/scroll.html

* less calculations in computeScroll()
* scrolling now is done in onScroll() and not in onDraw() anymore
* no more lagging when swiping horizontal and fling is triggered
* only one scroller left

but i have also some questions left, maybe you (@caske33 @lolobosse @alamkanak) can help a little bit:
* there are really a lot of calls of onFirstVisibleDayChanged if there is mScrollListener set while scrolling. i'm not sure how to but shouldn't this be called only after scroll/fling has finished?
* there are calls of canvas.drawRect for "hiding" everything drawn before, how about using clipRect to prevent from drawing in areas that should be empty?

### CODE REVIEW

**Comment by caske33** [comment]
I think that for the first question, the listener should be called everytime the first day changes, even while scrolling. That's how I would expect the listener to behave.

I'm not sure about the other question.

**Comment by marunjar** [comment]
ok, my intention was that the listener should only be called if the scrolling has finished because everthing called by this listener could block drawing and make scrolling less smooth.
i have no idea for any use case where you also need changes while scrolling.


the second question is obsolete. i read a little bit about drawing and the only benefit of using clipRect would be that you could use (semi)transparent headerRowBackgroundColor and nothing is drawn in back of header. i'll test it and create a new issue/pr if necessary.

**Comment by caske33** [comment]
The advantage of having it called everytime is that you can update something else in your GUI at the moment of changing. Maybe it's not really necessary, but I think doing it any other way would make the code also unnecessary more complex
+ If a user is holding down his finger mid-scroll, the whole UI is in a correct state. Otherwise, somethings might still show the old value from before the scrolling.

In the end, loadWeekViewEvents is also called during the drawing cycle and that is also blocking.

**Comment by marunjar** [comment]
ok, then i'm done for now.

if there's time for, can you please have a look at the changes and merge if everthing's ok?

**Comment by caske33** [comment]
@marunjar I've merged this. I only changed the snapping duration to be a bit shorter. Thanks for the great PR!

**Pull request merged**
