### PR TITLE
Show half hours

### PR DESCRIPTION
**Pull request by dgrant**
See screenshot for what the sample app looks like with showHalfHours set to true. Please let me know if there is anything wrong with this that would prevent it from being accepted. Thanks.

screenshot from 2015-03-27 11 23 35

### CODE REVIEW

**Comment by dgrant** [comment]
Thanks, I've made that change.

**Comment by dgrant** [comment]
Rebased

**Comment by caske33** [comment]
@dgrant Can you rebase this on develop and create a new PR that asks to merge this into develop instead of master?

**Comment by dgrant** [comment]
Started doing it and got a bunch of conflicts, fixed some, some remaining... have to run to Thanksgiving dinner.

**Comment by androidroadies** [comment]
Can you please provide a half hour working code.

**Comment by entropitor** [comment]
See the [Quivr-fork](https://github.com/Quivr/Android-Week-View), I believe we merged something similair  over there

**Comment by androidroadies** [comment]
Thanks...

**Pull request closed without merging**
