### PR TITLE
Add location field to WeekViewEvents

### PR DESCRIPTION
**Pull request by caske33**
(Copied most of the code from the AOSP: http://www.javased.com/index.php?source_dir=packages_apps_Calendar/src/com/android/calendar/DayView.java)

This will render the title in a bold typeface and the location in a normal typeface.

### CODE REVIEW

**Comment by alamkanak** [comment]
I think a better way to implement this will be to let the user chose the layout to inflate for the events. It is becoming to much specific, don't you think?

**Comment by caske33** [comment]
That's a possibility, but that makes it harder to implement and use this library, I think. A location is pretty standard, in my opinion (not useful for everyone, but for a lot of people). Especially since it used to be in the old Google Calendar style app.

**Comment by caske33** [comment]
@alamkanak The reason I'm still pro this commit is because 
1. location is pretty general. It's part of the ical format and it's also pretty important information, that should be distinct from the name of the event.
2. When it's done in the library, the library can ellipsize the text to use `...` in case the title and location combined don't fit in the event box.
3. Doing this in an inflated layout seems a lot harder, while the code to support this in the library is easy and maintainable.

**Comment by lolobosse** [comment]
@caske33, I'd also be pro this commit if you rename `bob` to `eventText` 😀

**Comment by lolobosse** [comment]
@alamkanak Inflating a layout would also be a very good solution. I think we need to make a new issue for that as `enhancement`

**Comment by caske33** [comment]
@lolobosse I changed it :wink:

**Comment by lolobosse** [comment]
:+1:

**Comment by caske33** [comment]
merged by #182

**Pull request closed without merging**
