### PR TITLE
Ability to turn off fling gesture

### PR DESCRIPTION
**Pull request by glennschmidt**
Fling can be disabled for the horizontal or vertical axis.

### CODE REVIEW

**Comment by caske33** [comment]
@glennschmidt Is it possible to also make this an option as an attribute?

**Comment by caske33** [comment]
@glennschmidt Can you fix it so this option can also be set via an attribute + rebase this on the latetst version of the develop branch?

**Comment by glennschmidt** [comment]
Ok, done

**Comment by caske33** [comment]
Rebased and merged by 8e6b482

**Pull request closed without merging**
