### PR TITLE
Documented the interfaces

### PR DESCRIPTION
**Pull request by lolobosse**
Hi there,

I was wondering why there is so much people asking how to load events in the view (including me at the beginning), so maybe with a better documentation of the interfaces, it could be better. We also could deploy a JavaDoc on the github subdomain of this library (I tested it there: http://meyer-laurent.com:3000/)

### CODE REVIEW

**Comment by caske33** [comment]
Very good PR. I'm pro having javadoc. The easiest way would be through the gh-pages branch, which should be updated on every release.

(Btw, maybe we should also update the readme, to put more emphasis on how to load events, because now it's just "implement the interface")

**Comment by lolobosse** [comment]
Ok, I'll include your advices then ! :+1: :smile:

**Comment by lolobosse** [comment]
Done, respecting your advices :+1: @alamkanak: do you want to create this branch for `gh-pages` or should I manage that (I've already done that with my lib)?

**Comment by caske33** [comment]
Super work, @lolobosse :smile:

**Comment by caske33** [comment]
@alamkanak This should be merged rather soon. I think it might solve a lot of issues.

**Comment by caske33** [comment]
I've merged this in the develop branch.

**Pull request merged**
