### PR TITLE
Update Paints

### PR DESCRIPTION
**Pull request by raplider**
Update Paints in setters

### CODE REVIEW

**Comment by caske33** [comment]
Minor issue, and I'm not really sure how @alamkanak stands on this, but try using spaces instead of tabs next time.

**Comment by alamkanak** [comment]
@raplider could you do another commit by fixing the tabs? also change the destination branch to `develop` if you can.

**Comment by caske33** [comment]
@alamkanak You can't change the destination branch in a github PR. You'd have to create a new PR.

**Comment by caske33** [comment]
@raplider Can you change this PR so it uses spaces instead of tabs?

**Comment by caske33** [comment]
I rebased this onto develop + tabs -> spaces in e7a2867

**Pull request closed without merging**
