### PR TITLE
PR of all my work for the Quivr fork of Android-Week-View

### PR DESCRIPTION
**Pull request by caske33**
I currently don't have the time to make a PR for all of the individual things I made. 

If this repo would have been more active when I was developing, seperate PRs would have been a possibility, but now I don't have the time or willingness to make a PR for all the different things I changed and fix things up to be as general as possible. 

This fork is in production by thousands of students everyday on our app Quivr for almost a year and there hasn't been a single complaint. So there's no question about the stability.

This PR provides for example a more flexible way of loading events (not just a monthloader) but also vertical zooming and a better coloring scheme. (look in the commits for all the other stuff, most our merge commits of other branches because of the seperate PR's I wanted to do originally, so also check those branches).

Everything is backwards compatible. So no problem there either.

But for example the weekends in the new (optional) coloring scheme is so that they always start on saturday and end on sunday. In the future this could be changed, but I think it's better if everything gets merged in the main repo first because other people can then work on it too + I can still help with this repo because my fork has diverged so hard that there are always merge conflicts if I want to cherry-pick commits from the main repo... So bascially, a NO now, also means that I cannot possibly contribute as much to this repo anymore.

@lolobosse @alamkanak Your thoughts?

If you're ok with merging, I'll do the effort of solving the merge conflict, but if it's a definite "NO" then I'm not going to put the extra work in up front...

### CODE REVIEW

**Comment by lolobosse** [comment]
Hey, I started review. It's so far ok but I have difficulties to understand every changes. Could you comment more? For instance, why is there two merge with `iss8-vertical-zooming`? 

Do you also updated the sample app in order that we can actually test the changes you made? (if not can you do this as well). So far I'm concerned, I've no problem with the PR idea, I just want to review the code properly and it doesn't seem to be possible yet because of a lack of comment/documentation: I see what the code does but I do not see why it should do that... :warning: 

I got your point about the fact that your fork diverged too much. That's definitely a problem that we should handle: as soon as there is a cool feature, just merge it! :rocket:

**Comment by caske33** [comment]
I'm not really sure why I merged iss8-vertical-zooming twice. I probably just lost the overview with all the branches. Especially because I was then still rebasing on master.

Is there a specific part that lacks documentation? Or in general?

I don't really use a lot of methods, but this is my weekview layout. Normally the sample application shouldn't need a lot of updating otherwise.
```
    <com.alamkanak.weekview.WeekView
        android:id="@+id/weekView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:eventTextColor="@android:color/white"
        app:headerColumnTextColor="#8f000000"
        app:todayHeaderTextColor="@color/blue"
        app:textSize="12sp"
        app:hourHeight="30dp"
        app:headerColumnPadding="4dp"
        app:headerRowPadding="12dp"
        app:columnGap="4dp"
        app:noOfVisibleDays="1"
        app:headerRowBackgroundColor="#ffefefef"
        app:headerColumnBackground="#ffffffff"
        app:xScrollingSpeed="0.1"
        app:futureBackgroundColor="#e8f9f9f9"
        app:pastBackgroundColor="#48f9f9f9"
        app:futureWeekendBackgroundColor="#90f9f9f9"
        app:pastWeekendBackgroundColor="#20f9f9f9"
        app:useNewColoringStyle="true"
        />
```

And it's not that I didn't make PRs back then. alamkank was just the only contributer back then and he didn't respond to my PRs.

**Comment by lolobosse** [comment]
@caske33 I know I was only explaining why the process was wrong not who we should blame for it. That has absolutely no importance, we need to get your work merged one way or another and it's a chance that I didn't really start to implement the all-day view :laughing:

**Comment by caske33** [comment]
haha, indeed :D

**Comment by caske33** [comment]
Are you stuck somewhere or did you just not have time to review them? Or is it ok now? @lolobosse

**Comment by lolobosse** [comment]
Tomorrow I have plenty of time, today will be complicated, I'm at work currently. :smile:

**Comment by marunjar** [comment]
:+1: can't wait for this to get merged and released

then i can switch back to this lib :)

**Comment by caske33** [comment]
@lolobosse Did you have time to look at it?

**Comment by lolobosse** [comment]
Not at all, doing some AngularJS shit. I do not think I’ll have time to do this at all. I think you can merge it and I’ll be using your lib and if I spot a bug, I’ll correct it via PR.


Laurent Meyer
TUM Student, Nerd, Coder, #Android, #Maker, TwitterAddict
Shore Dev Team
Tel: +4917661378768

**Comment by caske33** [comment]
@lolobosse @marunjar This should now be merged into the develop branch.

**Comment by marunjar** [comment]
thx

i'm just playing around with the changes and they're great (bob :smiley: :+1:)
theres a compile error #187 and a small bug with locations #188 

can you also have a look at the other pr and close the outdated ones?

**Comment by caske33** [comment]
I'll take a look tomorrow at your PRs and then see at the other issues and PRs and maybe mail alamkanak then to release a new version with all these features in it ;)

**Pull request merged**
