### PR TITLE
Save mHourHeigt to recover the last zoomed view

### PR DESCRIPTION
**Pull request by obaslan**

### CODE REVIEW

**Comment by caske33** [comment]
I'm not sure if this should be part of the library. I think the apps should implement this for themselves. @marunjar @lolobosse @alamkanak What's your opinion?

Besides that, you're only using the value in the sample app, so I'm not really sure why it saves the value in the library.

**Comment by obaslan** [comment]
There is currently no listener for the zoom, so I had to save the mHourHeight after a zoom is completed inside the library. I used the value in the sample app so we can try quickly to see that it works.

**Comment by caske33** [comment]
You can ask for the mHourHeight when you're activity ends using the getter and then use the setter during onCreate/onRestoreInstanceState/...

**Comment by obaslan** [comment]
Thanks @caske33 , that worked.

**Pull request closed without merging**
