### PR TITLE
Dynamic prefetch range.

### PR DESCRIPTION
**Pull request by caske33**
Solves #58

### CODE REVIEW

**Comment by caske33** [comment]
It would be super easy to also add a `StaticLoader` that always returns periodIndex 1. And only when periodIndex 1 is requested, will the loader call another method. Then people don't have the problem anymore that their events are rendered 3 times. (multiple issues reference this problem).
E.g. #81

**Comment by Soulcyber** [comment]
If this commit works (i dont have time to test it now) i think it could be very very usefull :)

**Comment by caske33** [comment]
I'm about to use this code (but with a different loader) in production for a couple thousands user every week. So it should normally work, pretty well :)

And thank you for acknowledging my work. I appreciate it!

**Comment by KimPark89** [comment]
I'm trying to testing this code but I don't understand how I can load only 1 month (instead of 3). Can you help me please @caske33?

**Comment by caske33** [comment]
@KimPark89 If you want to do that, you'll want to implement a WeekViewLoader that loads less than a month. (there will always be 3 periods loaded), but with this PR, you can choose how long those periods are. For example, I implemented a WeekViewLoader (in my own repo) that has a period for the first half of the month and the second half. 

But it would be easy to implement something that has periods of for example 10 days (and that would call a method with start and end date).

I'm probably gonna redo part of this PR, to have a more specific WeekViewLoader which would allow you to specify the amount of days to load at once. But as long as I don't get signals from @alamkanak about this being able to be merged, I'm not going to be putting the work in if I've no idea whether or not this will be used.

**Comment by caske33** [comment]
merged by #182

**Pull request closed without merging**
