### PR TITLE
add a getFirstVisibleHour method

### PR DESCRIPTION
**Pull request by caske33**

### CODE REVIEW

**Comment by QFNU-JWK** [comment]
Hi developer. If there is a function can set the visible hours during the day will be greater!

**Comment by caske33** [comment]
I'm not really sure what you mean by that.

**Comment by lolobosse** [comment]
Also not getting it, could you more precise?

**Comment by QFNU-JWK** [comment]
Sorry for my out of time replying.  I means that I holp developer can set the weekview visible hours range. Like I can set the hour range showing during the day.  0:00~5:00 can be hidden, 22:00~23:00 can be hidden, 6:00~21:00 show.

**Comment by caske33** [comment]
You should make an issue for that. Currently that's not possible.

**Comment by QFNU-JWK** [comment]
OK. Thanks very much.

**Pull request merged**
