### PR TITLE
Solved bug with view getting stuck between days.

### PR DESCRIPTION
**Pull request by caske33**
There was a bug where the weekview would get stuck between days. This is fixed with this commit. :grinning:

### CODE REVIEW

**Comment by alamkanak** [comment]
@caske33 How can I reproduce the defect?

**Comment by caske33** [comment]
I think this was if you scrolled really slowly and lifted your finger after you stopped moving (so you don't have a fling motion anymore).

**Comment by db-dblank** [comment]
Even with your solution my view get stuck between days. To reproduce just start scrolling horizontally and quickly lift your finger and press again.

**Comment by caske33** [comment]
With #182 it should be fixed, normally. I use it in production for over half a year and never had a complaint.

**Comment by caske33** [comment]
merged by #182

**Pull request closed without merging**
